// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type FooterDocumentDataSlicesSlice = FooterMenuSlice;

/**
 * Content for footer documents
 */
interface FooterDocumentData {
  /**
   * email field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  email: prismic.RichTextField;

  /**
   * phoneNumber field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.phonenumber
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phonenumber: prismic.RichTextField;

  /**
   * address field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;

  /**
   * Slice Zone field in *footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<FooterDocumentData>,
  'footer',
  Lang
>;

type HomeDocumentDataSlicesSlice =
  | DisplayOffersSlice
  | FaqSlice
  | NewsletterSlice
  | MostPopularCollectionSlice
  | ShowcaseCollectionnSlice
  | HeroSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<HomeDocumentData>,
  'home',
  Lang
>;

export type AllDocumentTypes = FooterDocument | HomeDocument;

/**
 * Primary content in *DisplayOffers → Items*
 */
export interface DisplayOffersSliceDefaultItem {
  /**
   * preheader field in *DisplayOffers → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: display_offers.items[].preheader
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  preheader: prismic.RichTextField;

  /**
   * header field in *DisplayOffers → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: display_offers.items[].header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.RichTextField;

  /**
   * description field in *DisplayOffers → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: display_offers.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * buttonText field in *DisplayOffers → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: display_offers.items[].buttontext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  buttontext: prismic.RichTextField;

  /**
   * buttonLink field in *DisplayOffers → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: display_offers.items[].buttonlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonlink: prismic.LinkField;

  /**
   * image field in *DisplayOffers → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: display_offers.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField;
}

/**
 * Default variation for DisplayOffers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DisplayOffersSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<DisplayOffersSliceDefaultItem>
>;

/**
 * Slice variation for *DisplayOffers*
 */
type DisplayOffersSliceVariation = DisplayOffersSliceDefault;

/**
 * DisplayOffers Shared Slice
 *
 * - **API ID**: `display_offers`
 * - **Description**: DisplayOffers
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DisplayOffersSlice = prismic.SharedSlice<'display_offers', DisplayOffersSliceVariation>;

/**
 * Primary content in *Faq → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Header field in *Faq → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Items*
 */
export interface FaqSliceDefaultItem {
  /**
   * title field in *Faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FaqSliceDefaultPrimary>,
  Simplify<FaqSliceDefaultItem>
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<'faq', FaqSliceVariation>;

/**
 * Primary content in *FooterMenu → Primary*
 */
export interface FooterMenuSliceDefaultPrimary {
  /**
   * Header field in *FooterMenu → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.RichTextField;
}

/**
 * Primary content in *FooterMenu → Items*
 */
export interface FooterMenuSliceDefaultItem {
  /**
   * listItem field in *FooterMenu → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.items[].listitem
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  listitem: prismic.RichTextField;

  /**
   * listItemLink field in *FooterMenu → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.items[].listitemlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  listitemlink: prismic.LinkField;
}

/**
 * Default variation for FooterMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterMenuSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FooterMenuSliceDefaultPrimary>,
  Simplify<FooterMenuSliceDefaultItem>
>;

/**
 * Slice variation for *FooterMenu*
 */
type FooterMenuSliceVariation = FooterMenuSliceDefault;

/**
 * FooterMenu Shared Slice
 *
 * - **API ID**: `footer_menu`
 * - **Description**: FooterMenu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterMenuSlice = prismic.SharedSlice<'footer_menu', FooterMenuSliceVariation>;

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultItem {
  /**
   * pageLink field in *Hero → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].pagelink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  pagelink: prismic.LinkField;

  /**
   * CollectionType field in *Hero → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].collectiontype
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  collectiontype: prismic.RichTextField;

  /**
   * Title field in *Hero → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Button field in *Hero → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].button
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  button: prismic.RichTextField;

  /**
   * image field in *Hero → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<HeroSliceDefaultItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Primary content in *MostPopularCollection → Primary*
 */
export interface MostPopularCollectionSliceDefaultPrimary {
  /**
   * Title field in *MostPopularCollection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: most_popular_collection.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * shopifyCollectionHandle field in *MostPopularCollection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: most_popular_collection.primary.shopifycollectionhandle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  shopifycollectionhandle: prismic.RichTextField;
}

/**
 * Default variation for MostPopularCollection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MostPopularCollectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<MostPopularCollectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MostPopularCollection*
 */
type MostPopularCollectionSliceVariation = MostPopularCollectionSliceDefault;

/**
 * MostPopularCollection Shared Slice
 *
 * - **API ID**: `most_popular_collection`
 * - **Description**: MostPopularCollection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MostPopularCollectionSlice = prismic.SharedSlice<
  'most_popular_collection',
  MostPopularCollectionSliceVariation
>;

/**
 * Primary content in *Newsletter → Primary*
 */
export interface NewsletterSliceDefaultPrimary {
  /**
   * instagram field in *Newsletter → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.primary.instagram
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkField;

  /**
   * facebook field in *Newsletter → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.primary.facebook
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  facebook: prismic.LinkField;

  /**
   * twitter field in *Newsletter → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.primary.twitter
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  twitter: prismic.LinkField;
}

/**
 * Default variation for Newsletter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<NewsletterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Newsletter*
 */
type NewsletterSliceVariation = NewsletterSliceDefault;

/**
 * Newsletter Shared Slice
 *
 * - **API ID**: `newsletter`
 * - **Description**: Newsletter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSlice = prismic.SharedSlice<'newsletter', NewsletterSliceVariation>;

/**
 * Primary content in *ShowcaseCollection → Items*
 */
export interface ShowcaseCollectionnSliceDefaultItem {
  /**
   * shopifyCollectionHandle field in *ShowcaseCollection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase_collectionn.items[].collectionhandle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  collectionhandle: prismic.RichTextField;

  /**
   * title field in *ShowcaseCollection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase_collectionn.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for ShowcaseCollection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShowcaseCollectionnSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<ShowcaseCollectionnSliceDefaultItem>
>;

/**
 * Slice variation for *ShowcaseCollection*
 */
type ShowcaseCollectionnSliceVariation = ShowcaseCollectionnSliceDefault;

/**
 * ShowcaseCollection Shared Slice
 *
 * - **API ID**: `showcase_collectionn`
 * - **Description**: ShowcaseCollectionn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShowcaseCollectionnSlice = prismic.SharedSlice<
  'showcase_collectionn',
  ShowcaseCollectionnSliceVariation
>;

/**
 * Default variation for Test Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Test*
 */
type TestSliceVariation = TestSliceDefault;

/**
 * Test Shared Slice
 *
 * - **API ID**: `test`
 * - **Description**: Test
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestSlice = prismic.SharedSlice<'test', TestSliceVariation>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      DisplayOffersSlice,
      DisplayOffersSliceDefaultItem,
      DisplayOffersSliceVariation,
      DisplayOffersSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimary,
      FaqSliceDefaultItem,
      FaqSliceVariation,
      FaqSliceDefault,
      FooterMenuSlice,
      FooterMenuSliceDefaultPrimary,
      FooterMenuSliceDefaultItem,
      FooterMenuSliceVariation,
      FooterMenuSliceDefault,
      HeroSlice,
      HeroSliceDefaultItem,
      HeroSliceVariation,
      HeroSliceDefault,
      MostPopularCollectionSlice,
      MostPopularCollectionSliceDefaultPrimary,
      MostPopularCollectionSliceVariation,
      MostPopularCollectionSliceDefault,
      NewsletterSlice,
      NewsletterSliceDefaultPrimary,
      NewsletterSliceVariation,
      NewsletterSliceDefault,
      ShowcaseCollectionnSlice,
      ShowcaseCollectionnSliceDefaultItem,
      ShowcaseCollectionnSliceVariation,
      ShowcaseCollectionnSliceDefault,
      TestSlice,
      TestSliceVariation,
      TestSliceDefault
    };
  }
}
